version: '3.9'

services:
  smiler-frontend: 
    ports:
      - ${FRONTEND_PORT}:80
    environment:
      FRONTEND_PORT: ${FRONTEND_PORT}
  smiler-backend:
    ports:
      - ${BACKEND_HOST_PORT}:${BACKEND_PORT}
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      BACKEND_HOST_PORT: ${BACKEND_HOST_PORT}