services:
  smiler-frontend:
    ports:
      - ${FRONTEND_PORT}:80
    environment:
      FRONTEND_PORT: ${FRONTEND_PORT}
  smiler-backend:
    ports:
      - ${BACKEND_HOST_PORT}:${BACKEND_PORT}
    environment:
      NODE_ENV: development
      BACKEND_PORT: ${BACKEND_PORT}
      BACKEND_HOST_PORT: ${BACKEND_HOST_PORT}
