const POSTS_INITIAL_COUNT = 20;
const POST_RATE_VALUE = 1;
const POST_MAX_SECTIONS = 8;
const POST_SECTION_TYPES = {
  TEXT: 'text',
  PICTURE: 'pic',
  VIDEO: 'vid',
};

const COMMENT_RATE_VALUE = 0.5;
const COMMENTS_INITIAL_COUNT = 10;

const USER_LOGIN_MODE = 0;
const USER_REG_MODE = 1;

const PASSWORD_MIN_LENGTH = 6;

const LOGIN_MIN_LENGTH = 3;
const LOGIN_MAX_LENGTH = 10;

export default {
  POSTS_INITIAL_COUNT,
  COMMENTS_INITIAL_COUNT,
  USER_LOGIN_MODE,
  USER_REG_MODE,
  PASSWORD_MIN_LENGTH,
  LOGIN_MIN_LENGTH,
  LOGIN_MAX_LENGTH,
  POST_RATE_VALUE,
  COMMENT_RATE_VALUE,
  POST_MAX_SECTIONS,
  POST_SECTION_TYPES
};
