const POSTS_INITIAL_COUNT = 20;
const COMMENTS_INITIAL_COUNT = 10;

const USER_LOGIN_MODE = 0;
const USER_REG_MODE = 1;

export default {
  POSTS_INITIAL_COUNT,
  COMMENTS_INITIAL_COUNT,
  USER_LOGIN_MODE,
  USER_REG_MODE,
};
